service: shoppingms
runtime: go
api_version: go1.8
env: flex

handlers:
- url: /.*
  script: _go_app

automatic_scaling:
  min_num_instances: 1

#[START cloudsql_settings]
# Replace INSTANCE_CONNECTION_NAME with the value obtained when configuring your
# Cloud SQL instance, available from the Google Cloud Console or from the Cloud SDK.
# For SQL v2 instances, this should be in the form of "project:region:instance".
# Cloud SQL v1 instances are not supported.
beta_settings:
  cloud_sql_instances: INSTANCE_CONNECTION_NAME
#[END cloudsql_settings]

